#
# profiling: Line by line profiling and code coverage for GAP
#
# Declarations
#

#! Arguments filename
#! @Description
#!   Parse <A>filename</A>, line by line profile previously generated by GAP.
DeclareGlobalFunction( "ReadLineByLineProfile" );

#! Arguments codecover, filename
#! @Description
#!   Generate a Flame graph from a previously parsed line by line profile <A>codecover</A> into file <A>filename</A>
DeclareGlobalFunction("OutputFlameGraph");

#! Arguments codecover, indir, outdir
#! @Description
#!   Output HTML files describing a line by line profile of all files contained in <A>indir</A> into the output directory <A>outdir</A>. The first <A>codecover</A> argument should be a profile previously read by <F>ReadLineByLineProfile</F>.
DeclareGlobalFunction("OutputAnnotatedCodeCoverageFiles");

